
[
  {
    "Name": "Water Polo Training Camp",
    "Image": "[Link](https://example.com/water-polo-training-camp)",
    "Available Seats": 100,
    "Price": "$150",
    "Video": "Link: [https://example.com/water-polo-training-camp-video]",
    "Description": "Join our intensive water polo training camp designed to enhance your skills and techniques in the pool.",
    "Instructor Name": "Coach Aqua",
    "Instructor Email": "coach.aqua@example.com",
    "Status": "Approved",
    "Submitted": "2024-03-19T08:00:00.000Z",
    "Total Enrolled": 50,
    "Reason": null
  },
  {
    "Name": "Water Polo Beginners' Clinic",
    "Image": "[Link](https://example.com/water-polo-beginners-clinic)",
    "Available Seats": 30,
    "Price": "$80",
    "Video": "Link: [https://example.com/water-polo-beginners-clinic-video]",
    "Description": "Learn the basics of water polo in our beginners' clinic. Perfect for newcomers looking to get started in the sport.",
    "Instructor Name": "Coach Splash",
    "Instructor Email": "coach.splash@example.com",
    "Status": "Approved",
    "Submitted": "2024-03-20T10:00:00.000Z",
    "Total Enrolled": 20,
    "Reason": null
  },
  {
    "Name": "Advanced Water Polo Techniques Workshop",
    "Image": "[Link](https://example.com/advanced-water-polo-techniques-workshop)",
    "Available Seats": 20,
    "Price": "$120",
    "Video": "Link: [https://example.com/advanced-water-polo-techniques-workshop-video]",
    "Description": "Take your water polo skills to the next level with our advanced techniques workshop. Open to experienced players.",
    "Instructor Name": "Coach Wave",
    "Instructor Email": "coach.wave@example.com",
    "Status": "Approved",
    "Submitted": "2024-03-21T13:00:00.000Z",
    "Total Enrolled": 15,
    "Reason": null
  },
  {
    "Name": "Water Polo Goalkeeping Masterclass",
    "Image": "[Link](https://example.com/water-polo-goalkeeping-masterclass)",
    "Available Seats": 15,
    "Price": "$100",
    "Video": "Link: [https://example.com/water-polo-goalkeeping-masterclass-video]",
    "Description": "Specialized training for water polo goalkeepers focusing on techniques, positioning, and game strategies.",
    "Instructor Name": "Coach Block",
    "Instructor Email": "coach.block@example.com",
    "Status": "Approved",
    "Submitted": "2024-03-22T15:00:00.000Z",
    "Total Enrolled": 10,
    "Reason": null
  },
  {
    "Name": "Water Polo Fitness Bootcamp",
    "Image": "[Link](https://example.com/water-polo-fitness-bootcamp)",
    "Available Seats": 40,
    "Price": "$90",
    "Video": "Link: [https://example.com/water-polo-fitness-bootcamp-video]",
    "Description": "Get in top shape for water polo season with our high-intensity fitness bootcamp tailored for water polo players.",
    "Instructor Name": "Coach Fit",
    "Instructor Email": "coach.fit@example.com",
    "Status": "Approved",
    "Submitted": "2024-03-23T09:00:00.000Z",
    "Total Enrolled": 25,
    "Reason": null
  },
  {
    "Name": "Water Polo Strategy Seminar",
    "Image": "[Link](https://example.com/water-polo-strategy-seminar)",
    "Available Seats": 25,
    "Price": "$110",
    "Video": "Link: [https://example.com/water-polo-strategy-seminar-video]",
    "Description": "Learn advanced water polo strategies and tactics from seasoned professionals in this informative seminar.",
    "Instructor Name": "Coach Strategy",
    "Instructor Email": "coach.strategy@example.com",
    "Status": "Approved",
    "Submitted": "2024-03-24T11:00:00.000Z",
    "Total Enrolled": 18,
    "Reason": null
  },
  {
    "Name": "Water Polo Scrimmage Camp",
    "Image": "[Link](https://example.com/water-polo-scrimmage-camp)",
    "Available Seats": 50,
    "Price": "$70",
    "Video": "Link: [https://example.com/water-polo-scrimmage-camp-video]",
    "Description": "Practice your water polo skills in real-game scenarios with our intense scrimmage camp. All levels welcome.",
    "Instructor Name": "Coach Scrimmage",
    "Instructor Email": "coach.scrimmage@example.com",
    "Status": "Approved",
    "Submitted": "2024-03-25T14:00:00.000Z",
    "Total Enrolled": 35,
    "Reason": null
  },
  {
    "Name": "Water Polo Goal Scoring Workshop",
    "Image": "[Link](https://example.com/water-polo-goal-scoring-workshop)",
    "Available Seats": 20,
    "Price": "$120",
    "Video": "Link: [https://example.com/water-polo-goal-scoring-workshop-video]",
    "Description": "Master the art of scoring goals in water polo with our specialized workshop focusing on shooting techniques.",
    "Instructor Name": "Coach Score",
    "Instructor Email": "coach.score@example.com",
    "Status": "Approved",
    "Submitted": "2024-03-26T16:00:00.000Z",
    "Total Enrolled": 12,
    "Reason": null
  },
  {
    "Name": "Water Polo Leadership Retreat",
    "Image": "[Link](https://example.com/water-polo-leadership-retreat)",
    "Available Seats": 30,
    "Price": "$100",
    "Video": "Link: [https://example.com/water-polo-leadership-retreat-video]",
    "Description": "Enhance your leadership skills both in and out of the pool with our immersive water polo leadership retreat.",
    "Instructor Name": "Coach Leader",
    "Instructor Email": "coach.leader@example.com",
    "Status": "Approved",
    "Submitted": "2024-03-27T10:00:00.000Z",
    "Total Enrolled": 22,
    "Reason": null
  }
]